version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 0
  reviewers:
  - AkMo3
  labels:
  - dependencies
  ignore:
  - dependency-name: "@testing-library/user-event"
    versions:
    - 13.1.2
    - 13.1.5
  - dependency-name: react-dom
    versions:
    - 17.0.2
  - dependency-name: react
    versions:
    - 17.0.2
  - dependency-name: web-vitals
    versions:
    - 1.1.1
